In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size = 10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[8217, 5376, 7994, 4547],
 [8217, 5376, 7994, 6052],
 [8217, 2690, 7994, 4272],
 [1072, 305, 5508, 3985, 9975],
 [1072, 305, 5508, 3985, 7383],
 [4838, 8217, 301, 7994, 2656],
 [9916, 4286, 8026, 3985]]

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 8217 5376 7994 4547]
 [   0    0    0    0 8217 5376 7994 6052]
 [   0    0    0    0 8217 2690 7994 4272]
 [   0    0    0 1072  305 5508 3985 9975]
 [   0    0    0 1072  305 5508 3985 7383]
 [   0    0    0 4838 8217  301 7994 2656]
 [   0    0    0    0 9916 4286 8026 3985]]


In [10]:
dim = 10

In [11]:
model = Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 193ms/step


array([[[-2.46180780e-02,  4.15370949e-02,  1.21122599e-03,
         -2.38743667e-02,  2.90383957e-02,  5.04884869e-03,
          1.04519129e-02, -4.48376536e-02,  1.44725554e-02,
         -4.22088057e-03],
        [-2.46180780e-02,  4.15370949e-02,  1.21122599e-03,
         -2.38743667e-02,  2.90383957e-02,  5.04884869e-03,
          1.04519129e-02, -4.48376536e-02,  1.44725554e-02,
         -4.22088057e-03],
        [-2.46180780e-02,  4.15370949e-02,  1.21122599e-03,
         -2.38743667e-02,  2.90383957e-02,  5.04884869e-03,
          1.04519129e-02, -4.48376536e-02,  1.44725554e-02,
         -4.22088057e-03],
        [-2.46180780e-02,  4.15370949e-02,  1.21122599e-03,
         -2.38743667e-02,  2.90383957e-02,  5.04884869e-03,
          1.04519129e-02, -4.48376536e-02,  1.44725554e-02,
         -4.22088057e-03],
        [ 4.88704555e-02, -4.57813852e-02,  1.16248839e-02,
         -8.99723917e-03, -3.57883088e-02,  3.39649990e-03,
          4.69566025e-02, -1.87358372e-02,  2.340370

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 8217, 5376, 7994, 4547], dtype=int32)

In [21]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step


array([[[-0.02461808,  0.04153709,  0.00121123, -0.02387437,
          0.0290384 ,  0.00504885,  0.01045191, -0.04483765,
          0.01447256, -0.00422088],
        [-0.02461808,  0.04153709,  0.00121123, -0.02387437,
          0.0290384 ,  0.00504885,  0.01045191, -0.04483765,
          0.01447256, -0.00422088],
        [-0.02461808,  0.04153709,  0.00121123, -0.02387437,
          0.0290384 ,  0.00504885,  0.01045191, -0.04483765,
          0.01447256, -0.00422088],
        [-0.02461808,  0.04153709,  0.00121123, -0.02387437,
          0.0290384 ,  0.00504885,  0.01045191, -0.04483765,
          0.01447256, -0.00422088],
        [ 0.04887046, -0.04578139,  0.01162488, -0.00899724,
         -0.03578831,  0.0033965 ,  0.0469566 , -0.01873584,
          0.02340371,  0.01874279],
        [ 0.00356512,  0.02944713,  0.03149355,  0.00645727,
          0.03980671,  0.00958117,  0.04418075, -0.00977843,
          0.00495397, -0.01454455],
        [ 0.01297568,  0.01316662,  0.00052788, -0.0